[metadata]
name = "yolov7_segmentation"
version = "1.0.1"
description = "This Picsellia pipeline trains YOLOv7 models for instance segmentation, detecting objects and generating pixel-perfect masks. YOLOv7 combines fast inference with accurate segmentation, making it ideal for real-time applications requiring both object detection and precise boundaries. Extended documentation is available here: https://github.com/picselliahq/picsellia-cv-pipelines/blob/main/pipelines/yolov7_segmentation/README.md"
type = "TRAINING"

[execution]
pipeline_script = "pipeline.py"
requirements_file = "pyproject.toml"
parameters_class = "utils/parameters.py:Yolov7HyperParameters"

[docker]
image_name = "picsellia/training-yolov7-segmentation"
image_tag = "1.0.1"

[model_version]
name = "segmentation"
origin_name = "YOLOv7"
framework = "PYTORCH"
inference_type = "SEGMENTATION"
