[metadata]
name = "yolov7_segmentation"
version = "1.0"
description = ""
type = "TRAINING"

[execution]
pipeline_script = "pipeline.py"
requirements_file = "pyproject.toml"
parameters_class = "utils/parameters.py:Yolov7HyperParameters"

[docker]
image_name = "picsellia/training-yolov7-segmentation"
image_tag = "latest"
