[metadata]
name = "yolov7_segmentation"
version = "1.0.1"
description = ""
type = "TRAINING"

[execution]
pipeline_script = "pipeline.py"
requirements_file = "pyproject.toml"
parameters_class = "utils/parameters.py:Yolov7HyperParameters"

[docker]
image_name = "picsellia/training-yolov7-segmentation"
image_tag = "1.0.1"

[model_version]
name = "segmentation"
origin_name = "YOLOv7"
framework = "PYTORCH"
inference_type = "SEGMENTATION"
