[metadata]
name = "clip-training"
version = "1.0.6"
description = "CLIP training pipeline"
type = "TRAINING"

[execution]
pipeline_script = "pipeline.py"
requirements_file = "pyproject.toml"
parameters_class = "utils/parameters.py:TrainingHyperParameters"

[docker]
image_name = "soniagrh/training-clip-2"
image_tag = "1.0.6"

[model_version]
name = "v2"
origin_name = "CLIP"
framework = "PYTORCH"
inference_type = "OBJECT_DETECTION"
