[metadata]
name = "clip-training"
version = "1.0.6"
description = "This Picsellia pipeline fine-tunes CLIP models using the Hugging Face Transformers library. CLIP learns to understand images through natural language descriptions, enabling zero-shot classification, image-text matching, and semantic search. Extended documentation availble here: https://github.com/picselliahq/picsellia-cv-pipelines/blob/main/pipelines/clip/training/README.md"
type = "TRAINING"

[execution]
pipeline_script = "pipeline.py"
requirements_file = "pyproject.toml"
parameters_class = "utils/parameters.py:TrainingHyperParameters"

[docker]
image_name = "picsellia/training-clip"
image_tag = "1.0.6"

[model_version]
name = "v1"
origin_name = "CLIP"
framework = "PYTORCH"
inference_type = "OBJECT_DETECTION"
