[project]
name = "training"
version = "0.1.0"
description = "CLIP fine-tuning pipeline"
requires-python = ">=3.10"

dependencies = [
    "picsellia-pipelines-cli",
    "picsellia-cv-engine[clip]"
]

[project.optional-dependencies]
clip = ["picsellia-cv-engine[clip]"]

[tool.uv.sources]
picsellia-cv-engine = { git = "https://github.com/picselliahq/picsellia-cv-engine.git", rev = "feat/add-clip-steps", extra = "clip"}
