[metadata]
name = "training"
version = "1.0"
description = "Training pipeline using YOLOV8."
type = "TRAINING"

[execution]
pipeline_script = "pipeline.py"
requirements_file = "pyproject.toml"
parameters_class = "utils/parameters.py:TrainingHyperParameters"

[docker]
image_name = ""
image_tag = ""

[model_version]
name = "v1"
origin_name = "DinoV2"
framework = "PYTORCH"
inference_type = "CLASSIFICATION"
