[metadata]
name = "mask_cropper"
version = "1.0"
description = "This pipeline processes data for X."
type = "DATASET_VERSION_CREATION"

[execution]
picsellia_pipeline_script = "picsellia_pipeline.py"
local_pipeline_script = "local_pipeline.py"
requirements_file = "pyproject.toml"
parameters_class = "utils/parameters.py:ProcessingParameters"

[docker]
image_name = "picsellia/mask-cropper-processing"
image_tag = "latest"
cpu = "12"
gpu = "0"
