[project]
name = "picsellia-cv-pipelines"
version = "0.1.0"
description = ""
authors = [
    {name = "SoniaGrh", email = "sonia.garrouch@hotmail.fr"}
]
requires-python = ">=3.10,<3.14"
readme = "README.md"

dependencies = [
    "picsellia-cv-engine",
    "picsellia-pipelines-cli>=0.7.4",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0"
]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
    "UP", # pyupgrade
]
ignore = [
    "E501",  # line too long, handled by black
]
