[metadata]
name = "fine_tuning"
version = "1.0.3"
description = "Training pipeline using YOLO and Ultralytics."
type = "TRAINING"

[execution]
pipeline_script = "pipeline.py"
requirements_file = "pyproject.toml"
parameters_class = "utils/parameters.py:TrainingHyperParameters"

[docker]
image_name = "picsellia/training-sam2"
image_tag = "1.0.3"

[model_version]
name = "v1"
origin_name = "SAM2"
framework = "PYTORCH"
inference_type = "SEGMENTATION"
