[metadata]
name = "yolov8-training"
version = "1.0"
description = "This pipeline processes data for X."
type = "TRAINING"

[execution]
pipeline_script = "pipeline.py"
requirements_file = "pyproject.toml"
parameters_class = "utils/parameters.py:UltralyticsHyperParameters"

[docker]
image_name = "picsellia/training-yolov8"
image_tag = "1.0"

[model_version]
name = "v1"
origin_name = "YOLOV8"
framework = "NOT_CONFIGURED"
inference_type = "MULTI"
