[metadata]
name = "training"
version = "1.0.0"
description = "Training pipeline using Mask R-CNN and PyTorch/TorchVision."
type = "TRAINING"

[execution]
pipeline_script = "pipeline.py"
requirements_file = "pyproject.toml"
parameters_class = "utils/parameters.py:TrainingHyperParameters"

[docker]
image_name = "picsellia/training-maskrcnn"
image_tag = "1.0.0"

[model_version]
name = "v1"
origin_name = "Mask-RCNN"
framework = "PYTORCH"
inference_type = "SEGMENTATION"
