[metadata]
name = "yolov8-pre-annotation"
version = "1.0"
description = "This pipeline processes data for X."
type = "PRE_ANNOTATION"

[execution]
pipeline_script = "pipeline.py"
requirements_file = "pyproject.toml"
parameters_class = "utils/parameters.py:ProcessingYOLOV8PreannotationParameters"


[docker]
image_name = "picsellia/preannotation-yolov8"
image_tag = "latest"
cpu = "8"
gpu = "1"
