[metadata]
name = "yolov8-pre-annotation"
version = "1.0"
description = "This pipeline processes data for X."
type = "PRE_ANNOTATION"

[execution]
picsellia_pipeline_script = "picsellia_pipeline.py"
local_pipeline_script = "local_pipeline.py"
requirements_file = "requirements.txt"

[docker]
image_name = "picsellia/preannotation-yolov8"
image_tag = "latest"
cpu = "8"
gpu = "1"
