[metadata]
name = "yolov8-pre-annotation"
version = "1.0.11"
description = "This Processing can be used to pre-annotate your Dataset by using a YOLOV8 Model Versions, a .pt file will be used to load the model and perform the infereces, this file will be retrieved though the parameter 'model_file_name'"
type = "PRE_ANNOTATION"

[execution]
pipeline_script = "pipeline.py"
requirements_file = "pyproject.toml"
parameters_class = "utils/parameters.py:ProcessingYOLOV8PreannotationParameters"
inputs_class = "utils/inputs.py:ProcessingInputs"

[docker]
image_name = "picsellia/yolov8-pre-annotation"
image_tag = "latest"
cpu = "8"
gpu = "1"
