[metadata]
name = "training"
version = "1.0.4"
description = "This Picsellia pipeline trains RT-DETR models using the Hugging Face Transformers library. RT-DETR is a real-time object detector that achieves excellent accuracy while maintaining high inference speed, making it ideal for production deployments. Extended documentation avaible here: https://github.com/picselliahq/picsellia-cv-pipelines/blob/main/pipelines/rt_detr/training/README.md"
type = "TRAINING"

[execution]
pipeline_script = "pipeline.py"
requirements_file = "pyproject.toml"
parameters_class = "utils/parameters.py:TrainingHyperParameters"

[docker]
image_name = "picsellia/training-rt-detr"
image_tag = "latest"

[model_version]
name = "v1"
origin_name = "RT-DETR"
framework = "PYTORCH"
inference_type = "OBJECT_DETECTION"
