[metadata]
name = "albumentations_processing"
version = "1.0"
description = "This pipeline processes data for X."
type = "DATASET_VERSION_CREATION"

[execution]
picsellia_pipeline_script = "picsellia_pipeline.py"
local_pipeline_script = "local_pipeline.py"
requirements_file = "pyproject.toml"
parameters_class = "utils/parameters.py:ProcessingParameters"

[docker]
image_name = "picsellia/albumentation-processing"
image_tag = "test"
cpu = "8"
gpu = "0"
