[metadata]
name = "SAM3_Bbox"
version = "1.0.1"
description = "This Picsellia pipeline uses Meta's SAM-3 (Segment Anything Model 3) to generate high-quality object detection annotations without requiring any training. Simply describe what you want to detect, and SAM-3 will find and segment those objects across your entire dataset. Extended documentation is available here: https://github.com/picselliahq/picsellia-cv-pipelines/blob/main/pipelines/SAM3_Bbox/README.md "
type = "PRE_ANNOTATION"

[execution]
pipeline_script = "pipeline.py"
requirements_file = "pyproject.toml"
parameters_class = "utils/parameters.py:ProcessingParameters"
inputs_class = "utils/inputs.py:ProcessingInputs"

[docker]
image_name = "picsellia/sam3-bbox-preannotation"
image_tag = "latest"
cpu = 4
gpu = 1
