[project]
name = "SAM3_Bbox"
version = "0.1.0"
description = "Picsellia processing pipeline"
requires-python = ">=3.10,<3.12"

dependencies = [
    "picsellia-pipelines-cli",
    "picsellia-cv-engine",
    "opencv-python",
    "transformers>=5.0.0rc1",
    "huggingface-hub",
    "torch",
    "torchvision",
    "shapely"
]
