[project]
name = "SAM3_Bbox"
version = "0.1.0"
description = "Picsellia processing pipeline with SAM3 for bbox"
requires-python = ">=3.14"

dependencies = [
    "picsellia-pipelines-cli",
    "picsellia-cv-engine @ git+https://github.com/picselliahq/picsellia-cv-engine.git@fix/handle-local-context-for-preannotation-without-modle-as-input",
    "opencv-python",
    "transformers>=5.0.0rc1",
    "huggingface-hub",
    "torch",
    "torchvision",
    "shapely"
]
