[metadata]
name = "Fast-Training-YoloV8"
version = "1.0"
description = "This pipeline processes data for X."
type = "TRAINING"

[execution]
picsellia_pipeline_script = "picsellia_pipeline.py"
local_pipeline_script = "local_pipeline.py"
requirements_file = "requirements.txt"

[docker]
image_name = "picsellia/fast-training-yolov8"
image_tag = "latest"
