name: Deploy pipelines to PROD

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    uses: ./.github/workflows/detect-pipeline-changes.yaml

  deploy-cpu-processing:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.processing_pipelines != '' && needs.detect-changes.outputs.processing_pipelines != '[]' }}
    uses: ./.github/workflows/deploy-env.yaml
    with:
      pipelines_json: ${{ needs.detect-changes.outputs.processing_pipelines }}
      hf_token_pipelines_json: ${{ needs.detect-changes.outputs.hf_token_pipelines }}
      organization: picsell
      environment_name: PROD
      bump: final
      runs_on: ubuntu-latest
    secrets:
      PXL_API_TOKEN: ${{ secrets.PXL_API_TOKEN_PROD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

  deploy-gpu-processing:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.gpu_processing_pipelines != '' && needs.detect-changes.outputs.gpu_processing_pipelines != '[]' }}
    uses: ./.github/workflows/deploy-env.yaml
    with:
      pipelines_json: ${{ needs.detect-changes.outputs.gpu_processing_pipelines }}
      hf_token_pipelines_json: ${{ needs.detect-changes.outputs.hf_token_pipelines }}
      organization: picsell
      environment_name: PROD
      bump: final
      runs_on: self-hosted
    secrets:
      PXL_API_TOKEN: ${{ secrets.PXL_API_TOKEN_PROD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

  deploy-training-processing:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.training_pipelines != '' && needs.detect-changes.outputs.training_pipelines != '[]' }}
    uses: ./.github/workflows/deploy-env.yaml
    with:
      pipelines_json: ${{ needs.detect-changes.outputs.training_pipelines }}
      hf_token_pipelines_json: ${{ needs.detect-changes.outputs.hf_token_pipelines }}
      organization: picsell
      environment_name: PROD
      bump: final
      runs_on: self-hosted
    secrets:
      PXL_API_TOKEN: ${{ secrets.PXL_API_TOKEN_PROD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
