name: CV Pipelines deploy (staging + prod)

on:
  push:
    branches:
      - main

jobs:
  detect-changed-pipelines:
    uses: ./.github/workflows/detect-pipeline-changes.yaml

  deploy-to-staging:
    needs: detect-changed-pipelines
    uses: ./.github/workflows/deploy-env.yaml
    with:
      pipelines_json: ${{ needs.detect-changed-pipelines.outputs.pipelines }}
      organization: test-account
      environment_name: STAGING
      bump: rc
    secrets:
      PXL_API_TOKEN: ${{ secrets.PXL_API_TOKEN_STAGING }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-to-prod:
    needs:
      - detect-changed-pipelines
      - deploy-to-staging
    if: ${{ needs.detect-changed-pipelines.outputs.pipelines != '' && needs.detect-changed-pipelines.outputs.pipelines != '[]' }}
    uses: ./.github/workflows/deploy-env.yaml
    with:
      pipelines_json: ${{ needs.detect-changed-pipelines.outputs.pipelines }}
      organization: picsell
      environment_name: PROD
      bump: final
    secrets:
      PXL_API_TOKEN: ${{ secrets.PXL_API_TOKEN_PROD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
