name: CV Pipelines test

on:
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    uses: ./.github/workflows/detect-pipeline-changes.yaml

  test-processing-pipelines:
    needs: detect-changes
    runs-on: ubuntu-latest

    if: ${{ needs.detect-changes.outputs.processing_pipelines != '' && needs.detect-changes.outputs.processing_pipelines != '[]' }}

    strategy:
      fail-fast: false
      matrix:
        pipeline: ${{ fromJson(needs.detect-changes.outputs.processing_pipelines) }}

    env:
      ORGANIZATION: test-account
      ENVIRONMENT: STAGING

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        run: pip install uv

      - name: Sync project dependencies
        run: uv sync

      - name: Run pipeline tests for one processing pipeline
        env:
          PXL_API_TOKEN: ${{ secrets.PXL_API_TOKEN_STAGING }}
        run: |
          PICSELLIA_CONFIG_DIR="$RUNNER_TEMP/picsellia_cfg"
          mkdir -p "$PICSELLIA_CONFIG_DIR"

          echo "PIPELINE=${{ matrix.pipeline }}"
          echo "ORG=$ORGANIZATION"
          echo "ENV=$ENVIRONMENT"
          echo "PICSELLIA_CONFIG_DIR=$PICSELLIA_CONFIG_DIR"

          uv run bash scripts/test_pipelines.sh \
            --pipeline "${{ matrix.pipeline }}" \
            --organization "$ORGANIZATION" \
            --env "$ENVIRONMENT" \
            --token "$PXL_API_TOKEN"
