[metadata]
name = "SAM3_polygons"
version = "1.0.7"
description = "This Dataset Processing provides polygons pre-labeling with SAM3. The annotation_mode parameter controls how new annotations interact with existing ones on an asset: 'keep' (do nothing if annotations already exist), 'replace' (delete existing annotations and overwrite them), or 'concatenate' (add new annotations alongside existing ones)."
type = "PRE_ANNOTATION"

[execution]
pipeline_script = "pipeline.py"
requirements_file = "pyproject.toml"
parameters_class = "utils/parameters.py:ProcessingParameters"
inputs_class = "utils/inputs.py:ProcessingInputs"

[docker]
image_name = "picsellia/sam3_polygons"
image_tag = "latest"
cpu = 4
gpu = 1
